### ISSUE TITLE
1.0.0 tasks roadmap

### ISSUE THREAD

**Issue by orangethewell** [orangethewell/open-witness-library#5]
# Overview

This is a general tasklist for tracking how close Open Witness Library is to a bible study program. Before asking or issuing a feature, check out there isn't one item that corresponds to your wished feature!

## Tasks

- [ ] Publication reading and study tools
    - [ ] Display publication text and content
       - [x] Display with same look and feel 
       - [x] Display text from publication document
       - [x] Display images from publication document
       - [ ] Display interactive content from publication document
          - [ ] Image Carroussels
          - [ ] Videos 
    - [ ] Study and notes
       - [ ] Show footnotes and user notes on study panel
       - [ ] Open references on study panel
       - [ ] Highlight publication text with colors
       - [ ] Create notes on highlights and paragraphs
       - [ ] Create note tags 
       - [ ] Save data on JW Library format for compatibility
    - [ ] Play audio files for publication if available 
- [ ] Bible Study
   - [ ] Display bible books like the original app
   - [ ] Show enhanced study notes (Study Bible)
   - [ ] Show index references
   - [ ] Show insight references
   - [ ] Compare different editions
      - [ ] Open verses on study panel
      - [ ] Check bibles installed
- [ ] Library
   - [ ] List all publications installed
      - [ ] List all `Bible (bi)` installed
      - [ ] List all `Insight (it)` installed
      - [ ] List all `Index (dx)` installed
      - [ ] List all `Watchtower (w)` installed
      - [ ] List all `Awake (g)` installed
      - [ ] List all `Kingdom Ministry (km)` installed
      - [x] List all `Books (bk)` installed
      - [ ] List all `Year Books (yb)` installed
      - [ ] List all `Brochures (brch)` installed
      - [ ] List all `Tracts (trct)` installed
      - [ ] List all `Program (pgm)` installed
      - [ ] List all `Meeting WorkBook (mwb)` installed
      - [ ] List all `Manual/Guidelines (manual)` installed
      - [ ] List all `Talk (talk)` installed
      - [ ] List all `Letter (letter)` installed
      - [ ] List all `Web (web)` installed
   - [ ] Show new publications
   - [ ] Download publications from website
   - [ ] Install publications (`*.jwpub` file)
   - [ ] Access or download publication through references
- [ ] Audio, video and media
   - [ ] Show publication videos on application (no redirect)
   - [ ] Show videos available
   - [ ] Create video playlists
   - [ ] Create image playlists
   - [ ] Show video or image in second screen if activated/available
